### ISSUE TITLE
页面显示Not Found

### ISSUE THREAD

**Issue by promayi** [lzdnico/subweb#6]
在局域网的一台linux (IP地址为192.168.123.7) 机器上按照步骤启动subweb
./subweb.sh http:127.0.0.1:10086 http:127.0.0.1:10010

然后通过其他windows机器去访问 http://192.168.123.7:10086/,  可以进入主页面，但是点击任何按钮都显示not found, 页面被指向去了http://192.168.123.7:10086/127.0.0.1:10086/basic

请问应该如何修改?   谢谢

**Comment by lzdnico** [comment]
@promayi ./subweb.sh http://127.0.0.1:10086 http://127.0.0.1:10010

**Comment by lzdnico** [comment]
@promayi ./subweb.sh http://192.168.123.7:10086 http://192.168.123.7:10010

**Comment by promayi** [comment]
可以了。多谢
