### ISSUE TITLE
绑定域名访问后能否禁止 ip:port 的访问？

### ISSUE THREAD

**Issue by Dukewill** [lzdnico/subweb#7]
请教一下，用 docker 部署并通过 nginx 转发实现了域名访问，这时 ip:port 仍然可以访问，怎样才能让 ip 访问不到呢？谢谢。

**Comment by lzdnico** [comment]
Disable 10086 10010 port of the server

**Comment by Dukewill** [comment]
I realized that it should be a nginx issue which has nothing to do with this project. Thx.

**Comment by wangfeng35** [comment]
> I realized that it should be a nginx issue which has nothing to do with this project. Thx.

[api.py](https://github.com/lzdnico/subweb/blob/admin/api.py)最后一行地址改成127.0.0.1就不会暴露了外网ip了 nginx设置反代即可
